/**
 * OnSite Excel Export Helpers
 *
 * Building blocks for branded Excel workbooks using xlsx.
 * Each app composes these helpers for its specific data format.
 *
 * Requires: xlsx (peer dependency)
 */

import { formatReportDate } from './branding';
import type { ColumnDef } from './types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Workbook = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Worksheet = any;

/**
 * Create a new workbook with an optional branded summary sheet.
 *
 * Dynamically imports xlsx to keep bundle size small.
 */
export async function createWorkbook(summary?: {
  title: string;
  rows: [string, string | number][];
  appName?: string;
}): Promise<{ wb: Workbook; XLSX: typeof import('xlsx') }> {
  const XLSX = await import('xlsx');
  const wb = XLSX.utils.book_new();

  if (summary) {
    const appName = summary.appName ?? 'OnSite Club';
    const data = [
      [`${appName} - ${summary.title}`],
      [''],
      ...summary.rows.map(([label, value]) => [label, value]),
      [''],
      ['Generated', formatReportDate(new Date())],
      [''],
      [`Generated by ${appName}`],
    ];

    const ws = XLSX.utils.aoa_to_sheet(data);
    ws['!cols'] = [{ wch: 20 }, { wch: 40 }];
    XLSX.utils.book_append_sheet(wb, ws, 'Summary');
  }

  return { wb, XLSX };
}

/**
 * Add a data sheet to a workbook.
 *
 * Supports both column definitions (for typed data) and raw arrays.
 */
export function addDataSheet(
  XLSX: typeof import('xlsx'),
  wb: Workbook,
  sheetName: string,
  data: Record<string, unknown>[],
  columns?: ColumnDef[]
): Worksheet {
  const cols: ColumnDef[] = columns ?? Object.keys(data[0] || {}).map(key => ({
    header: key,
    key,
  }));

  const headers = cols.map(c => c.header);
  const rows = data.map(row => cols.map(c => formatCellValue(row[c.key])));

  const wsData = [headers, ...rows];
  const ws = XLSX.utils.aoa_to_sheet(wsData);

  // Set column widths
  ws['!cols'] = cols.map(c => ({
    wch: c.width ?? Math.max(
      c.header.length,
      ...data.slice(0, 100).map(row => String(row[c.key] ?? '').length)
    ) + 2,
  }));

  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  return ws;
}

/**
 * Write workbook to buffer (for server-side API routes).
 */
export function workbookToBuffer(
  XLSX: typeof import('xlsx'),
  wb: Workbook
): Buffer {
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

/**
 * Download workbook as .xlsx file (browser only).
 */
export function downloadWorkbook(
  XLSX: typeof import('xlsx'),
  wb: Workbook,
  filename: string
): void {
  const cleanName = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  XLSX.writeFile(wb, cleanName);
}

/** Format a value for Excel cells */
function formatCellValue(value: unknown): string | number | boolean {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number') return value;
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}
