/**
 * WhatsApp — Format ReportModel as emoji-rich text for quick sharing.
 *
 * Designed for WhatsApp's markdown (bold with *, monospace with ```, etc.)
 * and copy-paste readability.
 *
 * Spec: 08-REPORTS.md "reporting/whatsapp.ts"
 */
import type { ReportModel, ReportDay } from '@onsite/shared';

/**
 * Format minutes as "Xh Ym".
 */
function formatDuration(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

/**
 * Get the type emoji for a day.
 */
function dayEmoji(day: ReportDay): string {
  switch (day.type) {
    case 'rain': return '\u{1F327}'; // 🌧
    case 'snow': return '\u{2744}\u{FE0F}'; // ❄️
    case 'sick': return '\u{1F912}'; // 🤒
    case 'dayoff': return '\u{1F3E0}'; // 🏠
    case 'holiday': return '\u{1F389}'; // 🎉
    default:
      if (day.totalMinutes === 0) return '\u{26AA}'; // ⚪ no hours
      if (day.totalMinutes > 600) return '\u{1F525}'; // 🔥 overtime >10h
      return '\u{2705}'; // ✅ normal work
  }
}

/**
 * Format a short day name (Mon, Tue, etc.).
 */
function shortDay(dateStr: string): string {
  const d = new Date(dateStr + 'T12:00:00');
  return d.toLocaleDateString('en-US', { weekday: 'short' });
}

/**
 * Format date as "Feb 10".
 */
function shortDate(dateStr: string): string {
  const d = new Date(dateStr + 'T12:00:00');
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

/**
 * Format ReportModel as WhatsApp-friendly text.
 */
export function formatWhatsApp(model: ReportModel): string {
  const lines: string[] = [];

  // Header
  lines.push(`\u{1F4CB} *Timesheet \u{2014} ${shortDate(model.period.start)} to ${shortDate(model.period.end)}*`);
  lines.push(`\u{1F477} ${model.worker.name}`);
  lines.push('');

  // Daily breakdown
  for (const day of model.days) {
    const emoji = dayEmoji(day);

    if (day.type !== 'work') {
      lines.push(`${emoji} ${shortDate(day.date)} (${shortDay(day.date)}) \u{2014} _${day.type}_`);
      continue;
    }

    const hours = formatDuration(day.totalMinutes);
    const breakStr = day.breakMinutes > 0 ? ` | \u{2615} ${day.breakMinutes}m` : '';
    const location = day.locationName ? ` | \u{1F4CD} ${day.locationName}` : '';

    lines.push(`${emoji} ${shortDate(day.date)} (${shortDay(day.date)})`);
    lines.push(`   \u{23F0} ${day.firstEntry} \u{2192} ${day.lastExit}${breakStr} | *${hours}*${location}`);
  }

  lines.push('');

  // Totals
  lines.push(`\u{1F4CA} *Total: ${model.totals.hours}h ${model.totals.minutes}m* (${model.totals.workDays} days)`);

  if (model.totals.breakMinutes > 0) {
    lines.push(`\u{2615} Breaks: ${formatDuration(model.totals.breakMinutes)}`);
  }

  if (model.totals.overtimeHours > 0) {
    lines.push(`\u{26A0}\u{FE0F} Overtime: ${model.totals.overtimeHours}h`);
  }

  // Weekly breakdown if multiple weeks
  if (model.weeklyTotals.length > 1) {
    lines.push('');
    lines.push('*Weekly:*');
    for (const week of model.weeklyTotals) {
      lines.push(`  \u{1F4C5} Week of ${shortDate(week.weekStart)}: *${formatDuration(week.totalMinutes)}*`);
    }
  }

  lines.push('');
  lines.push('_Generated by OnSite Timekeeper_');

  return lines.join('\n');
}

/**
 * Format a minimal plain text version (no emojis, for fallback).
 */
export function formatPlainText(model: ReportModel): string {
  const lines: string[] = [];

  lines.push(`TIMESHEET - ${model.worker.name}`);
  lines.push(`Period: ${model.period.start} to ${model.period.end}`);
  lines.push('');
  lines.push('Date        In     Out    Break  Total   Location');
  lines.push('-'.repeat(65));

  for (const day of model.days) {
    if (day.type !== 'work') {
      lines.push(`${day.date}  ${day.type.toUpperCase()}`);
      continue;
    }

    const breakStr = day.breakMinutes > 0 ? `${day.breakMinutes}m`.padEnd(6) : '  -   ';
    lines.push(
      `${day.date}  ${day.firstEntry.padEnd(6)} ${day.lastExit.padEnd(6)} ${breakStr} ${formatDuration(day.totalMinutes).padEnd(7)} ${day.locationName || ''}`,
    );
  }

  lines.push('-'.repeat(65));
  lines.push(`TOTAL: ${model.totals.hours}h ${model.totals.minutes}m  (${model.totals.workDays} days)`);

  if (model.totals.overtimeHours > 0) {
    lines.push(`OVERTIME: ${model.totals.overtimeHours}h`);
  }

  lines.push('');
  lines.push('Generated by OnSite Timekeeper');

  return lines.join('\n');
}
