/**
 * Legacy Styles - OnSite Timekeeper
 * 
 * Estilos mantidos para compatibilidade com versões anteriores
 * - manualEntryStyles: Form de entrada manual (versão antiga)
 * - compactStyles: Layout compacto (versão anterior ao v1.5)
 * 
 * ⚠️ DEPRECATED: Usar homeStyles (fixedStyles) para novas implementações
 */

import { StyleSheet, Platform, StatusBar } from 'react-native';
import { colors, withOpacity, shadows } from '../../../constants/colors';

// ============================================
// MANUAL ENTRY FORM STYLES (Legacy)
// ============================================

export const manualEntryStyles = StyleSheet.create({
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceMuted,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyLocations: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
  },
  emptyLocationsText: {
    fontSize: 14,
    color: colors.textSecondary,
    flex: 1,
  },
  formCard: {
    padding: 20,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.md,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 8,
  },
  dropdownSelected: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  dropdownDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  dropdownText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.text,
  },
  dropdownPlaceholder: {
    fontSize: 15,
    color: colors.textSecondary,
  },
  dropdownMenu: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
    overflow: 'hidden',
    ...shadows.sm,
  },
  dropdownOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownOptionActive: {
    backgroundColor: withOpacity(colors.primary, 0.08),
  },
  dropdownOptionText: {
    fontSize: 15,
    color: colors.text,
    flex: 1,
  },
  dropdownOptionTextActive: {
    fontWeight: '600',
    color: colors.primary,
  },
  dropdownAddOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 10,
    backgroundColor: colors.surfaceMuted,
  },
  dropdownAddText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.primary,
  },
  breakRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  breakInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  breakInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
    width: 70,
    backgroundColor: colors.surfaceMuted,
    color: colors.text,
  },
  breakUnit: {
    fontSize: 15,
    color: colors.textSecondary,
  },
  hint: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 16,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 12,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.buttonPrimaryText,
  },
  recentSection: {
    marginBottom: 16,
  },
  emptyRecent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    gap: 8,
  },
  emptyRecentText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 8,
    gap: 12,
  },
  recentDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  recentInfo: {
    flex: 1,
  },
  recentLocation: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 2,
  },
  recentTime: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  recentDuration: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  viewReportsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 4,
  },
  viewReportsText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
    flex: 1,
  },
});

// ============================================
// COMPACT STYLES (Legacy - kept for compatibility)
// ============================================

export const compactStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 8 : 50,
    paddingBottom: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  headerLogo: {
    width: 90,
    height: 28,
  },
  formCardLarge: {
    flex: 1,
    padding: 20,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
    ...shadows.md,
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  formTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  formTitleLarge: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  reportsLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: withOpacity(colors.primary, 0.1),
    borderRadius: 10,
  },
  reportsLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  inputLabelLarge: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dropdownLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
  },
  dropdownSelected: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  dropdownDotLarge: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  dropdownTextLarge: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
  },
  dropdownPlaceholder: {
    fontSize: 15,
    color: colors.textSecondary,
  },
  dropdownMenuLarge: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
    marginTop: -8,
    overflow: 'hidden',
    ...shadows.md,
  },
  dropdownOptionLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownOptionActive: {
    backgroundColor: withOpacity(colors.primary, 0.08),
  },
  dropdownOptionTextLarge: {
    fontSize: 15,
    color: colors.text,
    flex: 1,
  },
  dropdownOptionTextActive: {
    fontWeight: '600',
    color: colors.primary,
  },
  dropdownAddOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 10,
    backgroundColor: colors.surfaceMuted,
  },
  dropdownAddText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.primary,
  },
  timeRowLarge: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  timeFieldLarge: {
    flex: 1,
  },
  breakFieldLarge: {
    flex: 0.8,
  },
  timeInputRowLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeInputLarge: {
    width: 48,
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: 24,
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
  },
  timeSeparatorLarge: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
    marginHorizontal: 4,
  },
  breakInputLarge: {
    width: 56,
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: 24,
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
  },
  breakUnitLarge: {
    fontSize: 14,
    color: colors.textSecondary,
    marginLeft: 6,
  },
  saveButtonLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 8,
  },
  saveButtonTextLarge: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.buttonPrimaryText,
  },
  locationsSectionCompact: {
    marginBottom: 10,
  },
  sectionHeaderCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  sectionTitleCompact: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  addButtonCompact: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.surfaceMuted,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyLocationsCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
  },
  emptyLocationsTextCompact: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  locationCardsRowCompact: {
    flexDirection: 'row',
    gap: 8,
  },
  locationCardCompact: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 10,
  },
  locationCardHeaderCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 2,
  },
  locationCardNameCompact: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  locationCardTotalCompact: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  locationCardActiveCompact: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.success,
  },
  timerCardCompact: {
    padding: 12,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  timerCardActiveCompact: {
    borderLeftWidth: 3,
    borderLeftColor: colors.success,
  },
  timerRowActive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timerLeftActive: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  activeBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.successSoft,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
  },
  activeBadgeDotCompact: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: colors.success,
  },
  activeBadgeTextCompact: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.success,
  },
  timerCompact: {
    fontSize: 28,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    color: colors.text,
  },
  timerPausedCompact: {
    opacity: 0.4,
  },
  timerRightActive: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pausaInfoCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.surfaceMuted,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  pausaTimerCompact: {
    fontSize: 12,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    color: colors.textSecondary,
  },
  pausaTimerActiveCompact: {
    color: colors.accent,
  },
  timerActionsCompact: {
    flexDirection: 'row',
    gap: 6,
  },
  pauseBtnCompact: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resumeBtnCompact: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopBtnCompact: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.textSecondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerRowIdle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  idleBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.surfaceMuted,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
  },
  idleBadgeDotCompact: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: colors.textSecondary,
  },
  idleBadgeTextCompact: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  timerIdleCompact: {
    fontSize: 28,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    color: colors.textMuted,
  },
  startBtnCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  startBtnTextCompact: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.buttonPrimaryText,
  },
  timerWaitingCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 4,
  },
  timerWaitingTextCompact: {
    fontSize: 13,
    color: colors.textMuted,
  },
});
