/**
 * scripts/generate-css-vars.ts
 *
 * Reads `src/styles/tokens.ts`, scans the source tree for actual
 * `var(--token-name)` usage, and emits `src/styles/tokens.generated.css`
 * containing only the custom properties that are referenced.
 *
 * Fallback: if zero usage is found (common during refactor before components
 * adopt the tokens), emits the full `cssVars` block — PurgeCSS / esbuild
 * minifier removes the dead ones later in the Vite build.
 *
 * Design choice: no proper AST parser. A flat regex scan for `var(--foo)` is
 * enough because custom properties are a *stable surface* — the name in CSS
 * is always `--kebab-case`, never a dynamic expression. If we move to typed
 * getters (e.g. `tokens.shadow.key` at runtime) this script stops making sense
 * anyway — by then you're emitting inline styles, not CSS vars.
 *
 * Run: `npm run tokens` (auto-runs via prebuild).
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, extname, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cssVars } from '../src/styles/tokens';

const HERE = dirname(fileURLToPath(import.meta.url));
const CALC_ROOT = join(HERE, '..');
const SRC_DIR = join(CALC_ROOT, 'src');
const OUTPUT_PATH = join(SRC_DIR, 'styles', 'tokens.generated.css');
// Tokens.ts is the source-of-truth — its JSDoc examples reference var(--foo)
// and would register as false-positive usage. Skip it in the scan.
const TOKENS_SOURCE = join(SRC_DIR, 'styles', 'tokens.ts');

const SCAN_EXTENSIONS = new Set(['.ts', '.tsx', '.css', '.scss']);
const SKIP_DIRS = new Set(['node_modules', 'dist', 'build', '.next', '.turbo']);
const SKIP_FILES = new Set([OUTPUT_PATH, TOKENS_SOURCE]);
const VAR_PATTERN = /var\(\s*(--[a-z0-9-]+)/gi;

function* walk(dir: string): Generator<string> {
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.') || SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      yield* walk(full);
    } else {
      yield full;
    }
  }
}

function findUsedVars(): Set<string> {
  const used = new Set<string>();
  for (const file of walk(SRC_DIR)) {
    if (SKIP_FILES.has(file)) continue;
    if (!SCAN_EXTENSIONS.has(extname(file))) continue;
    const content = readFileSync(file, 'utf8');
    for (const match of content.matchAll(VAR_PATTERN)) {
      used.add(match[1]);
    }
  }
  return used;
}

function filterCssVars(block: string, allowed: Set<string>): string {
  const kept: string[] = [];
  for (const line of block.split('\n')) {
    const m = line.match(/^\s*(--[a-z0-9-]+)\s*:/i);
    if (!m) {
      // Preserve section comments + blank lines for readability.
      kept.push(line);
      continue;
    }
    if (allowed.has(m[1])) kept.push(line);
  }
  // Collapse runs of blank lines introduced by filtering.
  return kept.join('\n').replace(/\n{3,}/g, '\n\n');
}

const used = findUsedVars();
let body: string;
let mode: string;

if (used.size === 0) {
  mode = 'fallback — no var(--) usage found, emitting full set';
  body = cssVars;
} else {
  mode = `scan — ${used.size} tokens in use`;
  body = filterCssVars(cssVars, used);
}

const output = `/* AUTO-GENERATED by scripts/generate-css-vars.ts
   Mode: ${mode}
   Source: src/styles/tokens.ts
   Do not edit by hand — re-run \`npm run tokens\` or \`npm run build\`. */

:root {
${body}
}
`;

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, output);

const rel = relative(CALC_ROOT, OUTPUT_PATH).replace(/\\/g, '/');
console.log(`[tokens] ${mode}`);
console.log(`[tokens] wrote ${rel} (${output.length} bytes)`);
