/**
 * ARGUS Export Module
 * PDF and Excel export functionality for chat visualizations
 */

import type { ArgusMessage, ArgusVisualization } from '@/lib/supabase/schema';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type PDFDoc = any;

/**
 * Export conversation messages with visualizations to PDF
 */
export async function exportConversationToPDF(
  title: string,
  messages: ArgusMessage[]
): Promise<void> {
  // Dynamic import to reduce bundle size
  const jsPDFModule = await import('jspdf');
  const jsPDF = jsPDFModule.default;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let currentY = margin;

  // Helper to add new page if needed
  const checkPageBreak = (neededHeight: number) => {
    if (currentY + neededHeight > pageHeight - margin) {
      doc.addPage();
      currentY = margin;
      return true;
    }
    return false;
  };

  // Header
  doc.setFillColor(24, 24, 27); // zinc-900
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setTextColor(249, 115, 22); // orange-500
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('ARGUS', margin, 18);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Analytics Intelligence Report', margin, 26);

  // Report title
  doc.setTextColor(161, 161, 170); // zinc-400
  doc.setFontSize(8);
  doc.text(title, pageWidth - margin, 18, { align: 'right' });
  doc.text(new Date().toLocaleDateString('pt-BR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }), pageWidth - margin, 26, { align: 'right' });

  currentY = 45;

  // Process messages
  for (const message of messages) {
    if (message.role === 'user') {
      // User message
      checkPageBreak(20);
      doc.setFillColor(39, 39, 42); // zinc-800
      doc.roundedRect(margin, currentY, contentWidth, 15, 3, 3, 'F');
      doc.setTextColor(228, 228, 231); // zinc-200
      doc.setFontSize(10);
      doc.text(`Q: ${truncateText(message.content, 80)}`, margin + 5, currentY + 9);
      currentY += 20;
    } else if (message.visualization) {
      // Assistant message with visualization
      currentY = renderVisualization(doc, message.visualization, message.sql, margin, currentY, contentWidth, pageHeight, checkPageBreak);
    } else if (message.content) {
      // Plain text response
      checkPageBreak(25);
      doc.setTextColor(161, 161, 170);
      doc.setFontSize(9);
      const lines = doc.splitTextToSize(message.content, contentWidth - 10);
      doc.text(lines.slice(0, 6), margin + 5, currentY + 5);
      currentY += Math.min(lines.length, 6) * 5 + 10;
    }
  }

  // Footer on all pages
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(24, 24, 27);
    doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');
    doc.setTextColor(113, 113, 122); // zinc-500
    doc.setFontSize(8);
    doc.text('Generated by ARGUS - OnSite Club Analytics', margin, pageHeight - 6);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 6, { align: 'right' });
  }

  // Download
  doc.save(`${sanitizeFilename(title)}.pdf`);
}

/**
 * Render visualization to PDF
 */
function renderVisualization(
  doc: PDFDoc,
  viz: ArgusVisualization,
  sql: string | undefined | null,
  margin: number,
  startY: number,
  contentWidth: number,
  pageHeight: number,
  checkPageBreak: (height: number) => boolean
): number {
  let currentY = startY;

  // Visualization title
  checkPageBreak(30);
  doc.setFillColor(249, 115, 22); // orange-500
  doc.rect(margin, currentY, 3, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(viz.title || getTypeLabel(viz.type), margin + 8, currentY + 8);
  currentY += 18;

  switch (viz.type) {
    case 'metric':
      currentY = renderMetricPDF(doc, viz, margin, currentY, contentWidth);
      break;
    case 'table':
      currentY = renderTablePDF(doc, viz, margin, currentY, contentWidth, pageHeight, checkPageBreak);
      break;
    case 'chart':
      currentY = renderChartInfoPDF(doc, viz, margin, currentY, contentWidth);
      break;
    case 'alert':
      currentY = renderAlertPDF(doc, viz, margin, currentY, contentWidth, checkPageBreak);
      break;
    case 'user_card':
      currentY = renderUserCardPDF(doc, viz, margin, currentY, contentWidth);
      break;
  }

  // SQL query if present
  if (sql) {
    checkPageBreak(25);
    currentY += 5;
    doc.setFillColor(9, 9, 11); // zinc-950
    doc.roundedRect(margin, currentY, contentWidth, 20, 2, 2, 'F');
    doc.setTextColor(113, 113, 122);
    doc.setFontSize(7);
    doc.text('SQL Query:', margin + 3, currentY + 5);
    doc.setTextColor(161, 161, 170);
    doc.setFontSize(6);
    const sqlLines = doc.splitTextToSize(sql, contentWidth - 6);
    doc.text(sqlLines.slice(0, 3), margin + 3, currentY + 11);
    currentY += 25;
  }

  return currentY + 5;
}

function renderMetricPDF(
  doc: PDFDoc,
  viz: ArgusVisualization,
  margin: number,
  startY: number,
  contentWidth: number
): number {
  const data = viz.data as { value?: string | number; change?: number; changeLabel?: string }[] | undefined;
  const dataFirst = data?.[0];
  const value = viz.value || dataFirst?.value || '-';
  const change = dataFirst?.change;

  doc.setFillColor(39, 39, 42);
  doc.roundedRect(margin, startY, contentWidth, 30, 3, 3, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(String(value), margin + 10, startY + 20);

  if (change !== undefined) {
    const changeColor = change > 0 ? [34, 197, 94] : change < 0 ? [239, 68, 68] : [113, 113, 122];
    doc.setTextColor(changeColor[0], changeColor[1], changeColor[2]);
    doc.setFontSize(12);
    const changeText = `${change > 0 ? '+' : ''}${change}%${dataFirst?.changeLabel ? ` ${dataFirst.changeLabel}` : ''}`;
    doc.text(changeText, margin + 80, startY + 20);
  }

  doc.setFont('helvetica', 'normal');
  return startY + 35;
}

function renderTablePDF(
  doc: PDFDoc,
  viz: ArgusVisualization,
  margin: number,
  startY: number,
  contentWidth: number,
  _pageHeight: number,
  checkPageBreak: (height: number) => boolean
): number {
  if (!viz.data || !Array.isArray(viz.data) || viz.data.length === 0) {
    return startY;
  }

  const rows = viz.data as Record<string, unknown>[];
  const columns = viz.columns || Object.keys(rows[0]);
  const colWidth = contentWidth / columns.length;
  const rowHeight = 8;
  let currentY = startY;

  // Header
  checkPageBreak(rowHeight + 5);
  doc.setFillColor(39, 39, 42);
  doc.rect(margin, currentY, contentWidth, rowHeight, 'F');
  doc.setTextColor(161, 161, 170);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  columns.forEach((col: string, i: number) => {
    doc.text(truncateText(col.toUpperCase(), Math.floor(colWidth / 2)), margin + i * colWidth + 2, currentY + 5);
  });
  currentY += rowHeight;

  // Rows (max 15 for PDF)
  doc.setFont('helvetica', 'normal');
  const maxRows = Math.min(rows.length, 15);
  for (let r = 0; r < maxRows; r++) {
    checkPageBreak(rowHeight);
    const row = rows[r];
    if (r % 2 === 0) {
      doc.setFillColor(24, 24, 27);
      doc.rect(margin, currentY, contentWidth, rowHeight, 'F');
    }
    doc.setTextColor(228, 228, 231);
    doc.setFontSize(7);
    columns.forEach((col: string, i: number) => {
      const value = formatValue(row[col]);
      doc.text(truncateText(value, Math.floor(colWidth / 2)), margin + i * colWidth + 2, currentY + 5);
    });
    currentY += rowHeight;
  }

  if (rows.length > 15) {
    doc.setTextColor(113, 113, 122);
    doc.setFontSize(7);
    doc.text(`... and ${rows.length - 15} more rows`, margin, currentY + 5);
    currentY += 8;
  }

  return currentY + 5;
}

function renderChartInfoPDF(
  doc: PDFDoc,
  viz: ArgusVisualization,
  margin: number,
  startY: number,
  contentWidth: number
): number {
  doc.setFillColor(39, 39, 42);
  doc.roundedRect(margin, startY, contentWidth, 25, 3, 3, 'F');

  doc.setTextColor(161, 161, 170);
  doc.setFontSize(9);
  doc.text(`Chart Type: ${viz.chartType || 'line'}`, margin + 5, startY + 10);

  if (viz.data && Array.isArray(viz.data)) {
    doc.text(`Data Points: ${viz.data.length}`, margin + 5, startY + 18);
  }

  return startY + 30;
}

function renderAlertPDF(
  doc: PDFDoc,
  viz: ArgusVisualization,
  margin: number,
  startY: number,
  contentWidth: number,
  checkPageBreak: (height: number) => boolean
): number {
  const items = viz.items || [];
  let currentY = startY;

  for (const item of items) {
    checkPageBreak(15);
    doc.setFillColor(234, 179, 8, 0.2); // yellow with opacity
    doc.setDrawColor(234, 179, 8);
    doc.roundedRect(margin, currentY, contentWidth, 12, 2, 2, 'FD');
    doc.setTextColor(253, 224, 71); // yellow-300
    doc.setFontSize(8);
    doc.text(`! ${truncateText(item, 90)}`, margin + 5, currentY + 7);
    currentY += 15;
  }

  return currentY;
}

function renderUserCardPDF(
  doc: PDFDoc,
  viz: ArgusVisualization,
  margin: number,
  startY: number,
  contentWidth: number
): number {
  const dataArray = viz.data as {
    email?: string;
    name?: string;
    plan?: string;
    region?: string;
    sessions?: number;
    expected?: number;
  }[] | undefined;
  const data = dataArray?.[0];

  doc.setFillColor(39, 39, 42);
  doc.roundedRect(margin, startY, contentWidth, 35, 3, 3, 'F');

  // Avatar placeholder
  doc.setFillColor(249, 115, 22);
  doc.circle(margin + 15, startY + 17, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text('U', margin + 12, startY + 20);

  // User info
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(data?.name || 'Unknown User', margin + 30, startY + 12);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(161, 161, 170);
  doc.setFontSize(9);
  if (data?.email) {
    doc.text(data.email, margin + 30, startY + 20);
  }

  // Tags
  let tagX = margin + 30;
  const tagY = startY + 28;
  if (data?.plan) {
    doc.setFillColor(249, 115, 22);
    doc.roundedRect(tagX, tagY - 4, 30, 8, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.text(data.plan, tagX + 2, tagY + 2);
    tagX += 35;
  }
  if (data?.region) {
    doc.setTextColor(113, 113, 122);
    doc.setFontSize(7);
    doc.text(data.region, tagX, tagY + 2);
    tagX += 30;
  }
  if (data?.sessions !== undefined) {
    doc.setTextColor(161, 161, 170);
    doc.text(`${data.sessions} sessions`, tagX, tagY + 2);
  }

  return startY + 40;
}

/**
 * Export table data to Excel format (XLSX)
 */
export async function exportTableToExcel(
  title: string,
  data: Record<string, unknown>[]
): Promise<void> {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  // Dynamic import to reduce bundle size
  const XLSX = await import('xlsx');

  // Get columns from first row
  const columns = Object.keys(data[0]);

  // Create worksheet data with headers
  const wsData = [
    columns, // Header row
    ...data.map(row => columns.map(col => formatValueForExcel(row[col])))
  ];

  // Create worksheet
  const ws = XLSX.utils.aoa_to_sheet(wsData);

  // Set column widths
  const colWidths = columns.map(col => ({
    wch: Math.max(
      col.length,
      ...data.slice(0, 100).map(row => String(row[col] || '').length)
    ) + 2
  }));
  ws['!cols'] = colWidths;

  // Create workbook
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Data');

  // Add metadata sheet
  const metaWs = XLSX.utils.aoa_to_sheet([
    ['ARGUS Analytics Export'],
    [''],
    ['Report Title', title],
    ['Generated', new Date().toLocaleString('pt-BR')],
    ['Total Rows', data.length],
    ['Columns', columns.length],
    [''],
    ['Generated by ARGUS - OnSite Club Analytics'],
  ]);
  XLSX.utils.book_append_sheet(wb, metaWs, 'Info');

  // Download
  XLSX.writeFile(wb, `${sanitizeFilename(title)}.xlsx`);
}

/**
 * Export raw data as CSV
 */
export async function exportToCSV(
  title: string,
  data: Record<string, unknown>[]
): Promise<void> {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const columns = Object.keys(data[0]);

  // Build CSV content
  const csvRows = [
    columns.join(','), // Header
    ...data.map(row =>
      columns.map(col => {
        const value = row[col];
        const stringValue = formatValueForExcel(value);
        // Escape quotes and wrap in quotes if contains comma or newline
        if (stringValue.includes(',') || stringValue.includes('\n') || stringValue.includes('"')) {
          return `"${stringValue.replace(/"/g, '""')}"`;
        }
        return stringValue;
      }).join(',')
    )
  ];

  const csvContent = csvRows.join('\n');

  // Download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${sanitizeFilename(title)}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Helper functions

function getTypeLabel(type: ArgusVisualization['type']): string {
  switch (type) {
    case 'chart':
      return 'Chart';
    case 'table':
      return 'Data Table';
    case 'metric':
      return 'Metric';
    case 'alert':
      return 'Alert';
    case 'user_card':
      return 'User Info';
    default:
      return 'Result';
  }
}

function truncateText(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength - 3) + '...';
}

function sanitizeFilename(name: string): string {
  return name
    .replace(/[<>:"/\\|?*]/g, '-')
    .replace(/\s+/g, '_')
    .substring(0, 100);
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return '-';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'number') {
    if (Number.isInteger(value)) return value.toLocaleString();
    return value.toFixed(2);
  }
  if (value instanceof Date) return value.toLocaleDateString();
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

function formatValueForExcel(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'number') return String(value);
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}
